channels:
  - conda-forge
  - bioconda
dependencies:
  - r-rstac=1.0.1
  - r-tidyverse=2.0.0
  - r-stars=0.7-0
  - r-terra=1.8-93
  - r-httr2=1.2.2
  - r-fs=1.6.6
  - r-lobstr=1.1.3
  - r-biocmanager=1.30.27
  - bioconductor-rarr
  - sqlite=3.51.2
